tasks:
  - init: pip install -r requirements.txt
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - ms-pyright.pyright@1.1.121:+YXMIcpXG8dlDo7kaXSbbA==
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
    - pkief.material-icon-theme@4.5.0:ckDTVCTpdr4G0ZmIlQWkZA==